spring:
  application:
    name: demo-ai
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
      - classpath:db/callback
    url: jdbc:postgresql://localhost:5432/demoaidb
    user: postgres
    password: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/demoaidb
    username: postgres
    password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434/
      embedding:
        options:
          model: mxbai-embed-large
      chat:
        options:
          model: tinydolphin
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1024
        remove-existing-vector-store-table: true

logging:
  level:
    root: INFO
